P2_indices function documentation
IDEMSInternational/NCMPforRInstat pull request #2
Opened 2023-09-14 09:20 UTC by EVANSTATS

Hey @lilyclements check this and let me know if its okay.

2023-09-14 10:25 UTC, lilyclements requested changes

2023-09-14 10:25 UTC, lilyclements commented on R/p2_indices.R
> +#' This function is adapted from the ET-NCMP/NCMP project (https://github.com/ET-NCMP/NCMP) and modified for use in R-Instat.
Looks great - just the same two comments as the other PR.

1. Can you put this as a link, and put `@details` to be before `@examples`. 

To put as a link - 

\href{https://github.com/ET-NCMP/NCMP}{ET-NCMP/NCMP}

2023-09-14 13:43 UTC, EVANSTATS commented on R/p2_indices.R
> +#' This function is adapted from the ET-NCMP/NCMP project (https://github.com/ET-NCMP/NCMP) and modified for use in R-Instat.
Okay

2023-09-19 19:30 UTC, lilyclements approved these changes
Excellent stuff @EVANSTATS - well done

2023-09-19 19:30 UTC, merged