Exponential function documentation.
IDEMSInternational/NCMPforRInstat pull request #5
Opened 2023-09-18 09:38 UTC by EVANSTATS

Hello @lilyclements, have a look at this.

2023-09-18 09:49 UTC, EVANSTATS commented
I shouldn't have added changes to the DESCRIPTION file here. Kindly check it also. Am not sure if it was necessary but I kept getting a warning message. We can probably discuss this during a call.

2023-09-19 19:36 UTC, lilyclements commented on DESCRIPTION
> +    pacificclimate/climdex.pcic
@EVANSTATS nice! Good memory, and very observant!

2023-09-19 19:36 UTC, lilyclements commented on DESCRIPTION
> +    pacificclimate/climdex.pcic
@EVANSTATS only thing is that we want to have `climdex.pcic` in `Imports` too -

that is,

```
Imports: 
    climdex.pcic,
    magrittr,
Remotes:
    pacificclimate/climdex.pcic
```

2023-09-19 19:37 UTC, lilyclements requested changes
Minor comment, but very good stuff!

2023-09-25 09:41 UTC, EVANSTATS commented on DESCRIPTION
> +    pacificclimate/climdex.pcic
Aaah thank you.

2023-09-25 19:59 UTC, lilyclements approved these changes

2023-09-25 19:59 UTC, merged